version: '3.8'

services:
  agent_a:
    image: ollama/ollama:latest
    container_name: ai_agent_a
    ports:
      - "11434:11434"
    environment:
      OLLAMA_MODEL: llama3:8b
    volumes:
      - ollama_data_a:/root/.ollama
    deploy:
      resources:
        limits:
          memory: "8g"
          cpus: "2"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  agent_b:
    image: ollama/ollama:latest
    container_name: ai_agent_b
    ports:
      - "11435:11434"
    environment:
      OLLAMA_MODEL: deepseek-coder:6.7b
    volumes:
      - ollama_data_b:/root/.ollama
    deploy:
      resources:
        limits:
          memory: "8g"
          cpus: "2"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  agent_c:
    image: ollama/ollama:latest
    container_name: ai_agent_c
    ports:
      - "11436:11434"
    environment:
      OLLAMA_MODEL: phi3:mini
    volumes:
      - ollama_data_c:/root/.ollama
    deploy:
      resources:
        limits:
          memory: "4g"
          cpus: "1"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  quantize:
    image: ollama/quantize:latest
    container_name: ollama_quantize
    entrypoint: ["sh", "-c", "while true; do sleep 3600; done"]
    volumes:
      - ollama_data_quant:/root/.ollama
    deploy:
      resources:
        limits:
          memory: "2g"
          cpus: "0.5"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_mcp
    env_file:
      - .env
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: "2g"
          cpus: "1"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: "1g"
          cpus: "0.5"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  traefik:
    image: traefik:latest
    container_name: traefik_proxy
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --api.insecure=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_cert:/letsencrypt
    deploy:
      resources:
        limits:
          memory: "500m"
          cpus: "0.2"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  influxdb:
    image: influxdb:2.7
    container_name: influx_db
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: adminpass
      INFLUXDB_BUCKET: n8n_metrics
      INFLUXDB_ORG: team_bemini
    volumes:
      - influxdb_data:/var/lib/influxdb2
    deploy:
      resources:
        limits:
          memory: "500m"
          cpus: "0.5"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    deploy:
      resources:
        limits:
          memory: "500m"
          cpus: "0.5"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  ollama_data_a:
  ollama_data_b:
  ollama_data_c:
  ollama_data_quant:
  postgres_data:
  n8n_data:
  traefik_cert:
  influxdb_data:
  grafana_data: